//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9C4C62_globusEntities : DbContext
    {
        public DB_9C4C62_globusEntities()
            : base("name=DB_9C4C62_globusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<download> downloads { get; set; }
        public DbSet<home> homes { get; set; }
        public DbSet<project> projects { get; set; }
        public DbSet<slide> slides { get; set; }
        public DbSet<about> abouts { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<vision> visions { get; set; }
        public DbSet<hotline> hotlines { get; set; }
        public DbSet<skill> skills { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<service> services { get; set; }
    }
}
