//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vision
    {
        public int id { get; set; }
        public string vision1 { get; set; }
        public string des1 { get; set; }
        public string vision2 { get; set; }
        public string des2 { get; set; }
        public string vision3 { get; set; }
        public string des3 { get; set; }
    }
}
